# Generated by Django 2.2.5 on 2020-09-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('email', models.CharField(default='', max_length=50)),
                ('gender', models.CharField(default='', max_length=1)),
                ('certid', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Email',
        ),
    ]
