# Generated by Django 2.2.5 on 2020-09-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200908_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='certid',
            field=models.IntegerField(default=False, max_length=500),
        ),
    ]
